import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

import { TaskProvider } from './lib/providers/TaskProvider';
import { GlobalSettings } from './lib/providers/globalSettings';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <GlobalSettings>
          <TaskProvider>
            <header className="flex py-4 px-8">
              <Link href={'/profile/'} className="mr-auto">
                PF
              </Link>
              <div className="flex gap-2">
                <Link href={'/'}>Home</Link>
                <Link href={'/settings/'}>Settings</Link>
              </div>
            </header>
            {children}
          </TaskProvider>
        </GlobalSettings>
      </body>
    </html>
  );
}
